## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [5]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Развернуть вектор (первый становится последним)

In [6]:
arr[::-1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [7]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [8]:
arr = np.array([1, 2, 0, 0, 4, 0])
arr.nonzero()

(array([0, 1, 4]),)

Создать 3x3 единичную матрицу

In [9]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Создать массив 3x3x3 со случайными значениями

In [10]:
np.random.random(27).reshape(3, 3, 3)

array([[[0.78647544, 0.99770494, 0.14677826],
        [0.98222627, 0.53898825, 0.8379029 ],
        [0.99812687, 0.27654147, 0.32823662]],

       [[0.52473453, 0.20060988, 0.18611164],
        [0.49315973, 0.67853884, 0.10251609],
        [0.58429184, 0.4246442 , 0.71839601]],

       [[0.74505168, 0.77083341, 0.68266221],
        [0.23298104, 0.32205379, 0.72886809],
        [0.97165307, 0.89496875, 0.80830133]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [11]:
np.random.random(30).mean()

0.4747331373812046

Перемножить матрицы 5x3 и 3x2

In [12]:
A = np.arange(15).reshape(5, 3)
B = np.arange(6).reshape(3, 2)
print(A)
print(B)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]


In [13]:
# Solution 1
print(np.dot(A, B))

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [14]:
# Solution 2
print(A @ B)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [15]:
n = 10
arr = np.linspace(0, 1, num=n+2)[1:-1]
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Заменить максимальный элемент на ноль

In [16]:
arr[arr.argmax()] = 0
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.        ])

Преобразовать массив из float в int

In [17]:
arr.astype(int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [18]:
arr = np.arange(20).reshape(10, 2)
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [19]:
# Solution using numpy
def calculate_distances(X, Y):
    return np.sqrt(np.sum(X**2, axis=1) - 2 * np.dot(X, Y.T) + np.sum(Y**2, axis=1)[:, np.newaxis])
    
calculate_distances(arr, arr)

array([[ 0.        ,  2.82842712,  5.65685425,  8.48528137, 11.3137085 ,
        14.14213562, 16.97056275, 19.79898987, 22.627417  , 25.45584412],
       [ 2.82842712,  0.        ,  2.82842712,  5.65685425,  8.48528137,
        11.3137085 , 14.14213562, 16.97056275, 19.79898987, 22.627417  ],
       [ 5.65685425,  2.82842712,  0.        ,  2.82842712,  5.65685425,
         8.48528137, 11.3137085 , 14.14213562, 16.97056275, 19.79898987],
       [ 8.48528137,  5.65685425,  2.82842712,  0.        ,  2.82842712,
         5.65685425,  8.48528137, 11.3137085 , 14.14213562, 16.97056275],
       [11.3137085 ,  8.48528137,  5.65685425,  2.82842712,  0.        ,
         2.82842712,  5.65685425,  8.48528137, 11.3137085 , 14.14213562],
       [14.14213562, 11.3137085 ,  8.48528137,  5.65685425,  2.82842712,
         0.        ,  2.82842712,  5.65685425,  8.48528137, 11.3137085 ],
       [16.97056275, 14.14213562, 11.3137085 ,  8.48528137,  5.65685425,
         2.82842712,  0.        ,  2.82842712

In [20]:
# Check with scipy package
from scipy.spatial.distance import cdist

cdist(arr, arr)

array([[ 0.        ,  2.82842712,  5.65685425,  8.48528137, 11.3137085 ,
        14.14213562, 16.97056275, 19.79898987, 22.627417  , 25.45584412],
       [ 2.82842712,  0.        ,  2.82842712,  5.65685425,  8.48528137,
        11.3137085 , 14.14213562, 16.97056275, 19.79898987, 22.627417  ],
       [ 5.65685425,  2.82842712,  0.        ,  2.82842712,  5.65685425,
         8.48528137, 11.3137085 , 14.14213562, 16.97056275, 19.79898987],
       [ 8.48528137,  5.65685425,  2.82842712,  0.        ,  2.82842712,
         5.65685425,  8.48528137, 11.3137085 , 14.14213562, 16.97056275],
       [11.3137085 ,  8.48528137,  5.65685425,  2.82842712,  0.        ,
         2.82842712,  5.65685425,  8.48528137, 11.3137085 , 14.14213562],
       [14.14213562, 11.3137085 ,  8.48528137,  5.65685425,  2.82842712,
         0.        ,  2.82842712,  5.65685425,  8.48528137, 11.3137085 ],
       [16.97056275, 14.14213562, 11.3137085 ,  8.48528137,  5.65685425,
         2.82842712,  0.        ,  2.82842712

Случайно расположить p элементов в 2D массив

In [21]:
p = 20
arr = np.arange(p)

result_arr = np.random.choice(arr, p, replace = False).reshape(-1, 2)
result_arr

array([[ 1, 19],
       [ 8,  0],
       [10, 12],
       [ 4, 17],
       [16, 11],
       [13, 15],
       [14,  2],
       [ 5,  6],
       [18,  9],
       [ 7,  3]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [22]:
arr = np.arange(1, 6)
arr_len = arr.size
print(arr)

[1 2 3 4 5]


In [23]:
zeros_arr = np.zeros(arr_len * 3).reshape(arr_len, 3)
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
result_arr = np.hstack((arr.reshape(-1, 1), zeros_arr)).flatten()
result_arr

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.,
       0., 0., 0.])

Найти наиболее частое значение в массиве

In [25]:
values, counts = np.unique(result_arr, return_counts = True)
print(values)
print(counts)

mode = values[counts.argmax()]
mode

[0. 1. 2. 3. 4. 5.]
[15  1  1  1  1  1]


0.0

Найти n наибольших значений в массиве

In [26]:
n = 3
unique_values = np.unique(result_arr)
unique_values.argsort()[::-1][:n]

array([5, 4, 3])

## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [27]:
import pandas as pd

food = pd.read_csv('./data/en.openfoodfacts.org.products.tsv.zip', sep='\t', compression='zip', low_memory=False)

Посмотреть первые 5 записей

In [28]:
food.head(5)

code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [29]:
food.shape[0]

356027

Сколько столбцов в наборе данных?

In [30]:
food.shape[1]

163

Напечатайте все названия столбцов

In [31]:
food_columns = food.columns.values
food_columns

array(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity', 'packaging', 'packaging_tags',
       'brands', 'brands_tags', 'categories', 'categories_tags',
       'categories_en', 'origins', 'origins_tags', 'manufacturing_places',
       'manufacturing_places_tags', 'labels', 'labels_tags', 'labels_en',
       'emb_codes', 'emb_codes_tags', 'first_packaging_code_geo',
       'cities', 'cities_tags', 'purchase_places', 'stores', 'countries',
       'countries_tags', 'countries_en', 'ingredients_text', 'allergens',
       'allergens_en', 'traces', 'traces_tags', 'traces_en',
       'serving_size', 'no_nutriments', 'additives_n', 'additives',
       'additives_tags', 'additives_en', 'ingredients_from_palm_oil_n',
       'ingredients_from_palm_oil', 'ingredients_from_palm_oil_tags',
       'ingredients_that_may_be_from_palm_oil_n',
       'ingredients_that_may_be_from_palm_oil',
   

Какое название у 105 столбца?

In [32]:
# Considering Python array indexing from zero

food_columns[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [33]:
# Considering Python array indexing from zero

food[food_columns[104]].dtype

dtype('float64')

Как проиндексирован набор данных?

In [34]:
food.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [35]:
# Considering Python array indexing from zero

food.iloc[18]['product_name']

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [36]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep='\t')

Как много продуктов стоят более чем $10.00?

In [37]:
chipo['item_price'] = chipo['item_price'].apply(lambda x: x.strip('$')).astype(float)
chipo[chipo['item_price'] > 10].shape[0]

1130

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [38]:
chipo[['item_name', 'item_price']]

item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
5                              Chicken Bowl       10.98
6                             Side of Chips        1.69
7                             Steak Burrito       11.75
8                          Steak Soft Tacos        9.25
9                             Steak Burrito        9.25
10                      Chips and Guacamole        4.45
11                     Chicken Crispy Tacos        8.75
12                       Chicken Soft Tacos        8.75
13                             Chicken Bowl       11.25
14                      Chips and Guacamole        4.45
15    Chips and Tomatillo-Green Chili Salsa        2.39
16                          Chicken Burrito        8.49
17                          Chicken Burrito        8.49
18                              Canned Soda        2.18
19                             Chicken Bowl        8.75
20                      Chips and Guacamole        4.45
21                         Barbacoa Burrito        8.99
22                         Nantucket Nectar        3.39
23                          Chicken Burrito       10.98
24                                     Izze        3.39
25             Chips and Fresh Tomato Salsa        2.39
26                             Chicken Bowl        8.49
27                         Carnitas Burrito        8.99
28                              Canned Soda        1.09
29                          Chicken Burrito        8.49
...                                     ...         ...
4592                       Barbacoa Burrito       11.75
4593                          Carnitas Bowl       11.75
4594                          Barbacoa Bowl       11.75
4595                           Chicken Bowl        8.75
4596                    Chips and Guacamole        4.45
4597                      Canned Soft Drink        1.25
4598                          Bottled Water        1.50
4599                           Chicken Bowl        8.75
4600                    Chips and Guacamole        4.45
4601                      Canned Soft Drink        1.25
4602                       Barbacoa Burrito        9.25
4603                       Barbacoa Burrito        9.25
4604                           Chicken Bowl        8.75
4605                    Chips and Guacamole        4.45
4606                      Canned Soft Drink        1.25
4607                          Steak Burrito       11.75
4608                         Veggie Burrito       11.25
4609                      Canned Soft Drink        1.25
4610                          Steak Burrito       11.75
4611                         Veggie Burrito       11.25
4612                          Carnitas Bowl        9.25
4613                                  Chips        2.15
4614                          Bottled Water        1.50
4615                     Chicken Soft Tacos        8.75
4616                    Chips and Guacamole        4.45
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

Отсортировать по имени предмета

In [39]:
chipo.sort_values('item_name', ascending=True)

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description  item_price  
3389                                        [Diet Coke]       12.98  
341                                         [Diet Coke]        6.49  
1849                                             [Coke]        6.49  
1860                                        [Diet Coke]        6.49  
2713                                             [Coke]        6.49  
3422                                             [Coke]        6.49  
553                                         [Diet Coke]        6.49  
1916                                        [Diet Coke]        6.49  
1922                                             [Coke]        6.49  
1937                                        [Diet Coke]        6.49  
3836                                             [Coke]        6.49  
298                                            [Sprite]        6.49  
1976                                        [Diet Coke]        6.49  
1167                                             [Coke]        6.49  
3875                                     

Сколько было заказано самого дорогого предмета?

In [40]:
# Find the most expensive item

exp_item_name = chipo.iloc[chipo['item_price']/chipo['quantity'].idxmax()]['item_name'].unique()[0]
exp_item_name

'Chips and Fresh Tomato Salsa'

In [41]:
# Considering quantity in calculation

chipo[chipo['item_name'] == exp_item_name]['quantity'].sum()

130

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [42]:
# Considering quontity in calculation

chipo[chipo['item_name'] == 'Veggie Salad Bowl']['quantity'].sum()

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [43]:
# Calculating orders count with selected item count > 1 in order

chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)].shape[0]

20